---
- name: ALERTMANAGER | Check for prometheus user
  getent:
    database: passwd
    key: "{{ alertmanager_user }}"
    fail_key: False

- name: ALERTMANAGER | Check for prometheus group
  getent:
    database: passwd
    key: "{{ alertmanager_group }}"
    fail_key: False

- name: ALERTMANAGER | Ensure Alertmanager group
  group:
    name: "{{ alertmanager_group }}"
    system: yes
    state: present
  when: getent_passwd[alertmanager_group] == none

- name: ALERTMANAGER | Ensure Alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    comment: "alertmanager user account"
    createhome: no
    system: yes
    shell: /bin/false
  when: getent_passwd[alertmanager_user] == none

- include_tasks: install-alertmanager.yml
  static: no

- name: ALERTMANAGER | Configure systemd service
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: alertmanager